version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gomailer_api
    ports:
      - "9000:9000" # TCP port
      - "9091:9091" # Metrics port
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=admin
      - RABBITMQ_PASSWORD=admin
    depends_on:
      - rabbitmq
    networks:
      - gomailer_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: gomailer_rabbitmq
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management interface port
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - gomailer_network

  prometheus:
    image: prom/prometheus:latest
    container_name: gomailer_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    networks:
      - gomailer_network

  grafana:
    image: grafana/grafana:latest
    container_name: gomailer_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - gomailer_network

networks:
  gomailer_network:
    driver: bridge

volumes:
  rabbitmq_data:
  prometheus_data:
  grafana_data:
