version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: gomailer_rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management interface port
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - gomailer_network

networks:
  gomailer_network:
    driver: bridge

volumes:
  rabbitmq_data: 