version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.tls
    container_name: gomailer_api_tls
    ports:
      - "9000:9000" # TLS port
      - "9091:9091" # Metrics port
    environment:
      # RabbitMQ Configuration
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=admin
      - RABBITMQ_PASSWORD=admin

      # TLS Configuration (Secure)
      - TCP_ENABLED=false
      - TCP_TLS_ENABLED=true
      - TCP_TLS_CERT_PATH=certs/server.crt
      - TCP_TLS_KEY_PATH=certs/server.key
      - TCP_TLS_CA_PATH=certs/ca-cert.pem

      # Auth Secret (should be overridden with secure value)
      - TCP_AUTH_SECRET=docker-tls-secret-change-me

    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - gomailer_tls_network
    # Add health check for TLS service
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "echo 'quit' | openssl s_client -connect localhost:9000 -ign_eof",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: gomailer_rabbitmq_tls
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management interface port
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - rabbitmq_tls_data:/var/lib/rabbitmq
    networks:
      - gomailer_tls_network

  prometheus:
    image: prom/prometheus:latest
    container_name: gomailer_prometheus_tls
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - api
    networks:
      - gomailer_tls_network

  grafana:
    image: grafana/grafana:latest
    container_name: gomailer_grafana_tls
    ports:
      - "3000:3000"
    volumes:
      - grafana_tls_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    networks:
      - gomailer_tls_network

networks:
  gomailer_tls_network:
    driver: bridge

volumes:
  rabbitmq_tls_data:
  prometheus_tls_data:
  grafana_tls_data:
