global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "gomailer"
    static_configs:
      - targets: ["host.docker.internal:9091"] # Metrics endpoint port
    metrics_path: "/metrics"
