global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "gomailer"
    static_configs:
      - targets: ["host.docker.internal:8080"] # Assuming metrics endpoint is exposed on the API port
    metrics_path: "/metrics"
