apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prometheus
    url: http://prometheus:9090
    jsonData:
      timeInterval: "5s"
    isDefault: true
    editable: false
